# Simple configuration for "blocklist-v2" that uses alternative resolvers for
# queries that match the allowlist or blocklist. The default behavior is to
# return NXDOMAIN for any item that matches the blocklist but not the allowlist.
# With resolvers, it's possible to send queries to different resolvers based
# on them matching the allowlist or blocklist. Similar to a router.

[resolvers.cloudflare-dot]
address = "1.1.1.1:853"
protocol = "dot"

[resolvers.google-dot]
address = "8.8.8.8:853"
protocol = "dot"

[groups.cloudflare-blocklist]
type             = "blocklist-v2"
resolvers        = ["cloudflare-dot"] # Default upstream resolver for anything not matching either list
blocklist-resolver = "google-dot" # Resolver used for anything matching the blocklist (and not on the allowlist)
blocklist-format = "domain"
blocklist = [
  'evil.com',
  '.facebook.com',
  '*.twitter.com',
]
allowlist-resolver = "cloudflare-dot" # Resolver for anything on the allowlist
allowlist-format = "domain"
allowlist = [                # Allowlist items override/bypass blocklist items
  'allowed.facebook.com',
]

[listeners.local-udp]
address = ":53"
protocol = "udp"
resolver = "cloudflare-blocklist"

[listeners.local-tcp]
address = ":53"
protocol = "tcp"
resolver = "cloudflare-blocklist"
