# This config starts a UDP and a TCP resolver on the loopback interface for plain DNS.
# All queries are forwarded to a local DNS-over-QUIC server.

[resolvers.local-doq]
address = "server.acme.test:1784"
protocol = "doq"
ca = "example-config/server.crt"
bootstrap-address = "127.0.0.1"

[listeners.local-udp]
address = "127.0.0.1:53"
protocol = "udp"
resolver = "local-doq"

[listeners.local-tcp]
address = "127.0.0.1:53"
protocol = "tcp"
resolver = "local-doq"
