
# into DNS-over-TLS queries to Cloudflare's DNS server.
[bootstrap-resolver]
address = "1.1.1.1:853"
protocol = "dot"

[resolvers.cloudflare-dot]
address = "gcp.ctptech.dev:853"
protocol = "dot"

[listeners.local-udp]
address = ":53"
protocol = "udp"
resolver = "sub-domain-replace"

[listeners.local-tcp]
address = ":53"
protocol = "tcp"
resolver = "sub-domain-replace"

# must have dots on both ends to work
[groups.sub-domain-replace]
  type = "subdomain-replace"
  resolvers = [ "cloudflare-dot" ]
  subdomain = [

    { from = '.ctptech.dev.', to = '.whiskey.software.' },
    { from = '.whiskey.software.', to = '.charlesp.tech.' },
    { from = '.whisky.software.', to = '.whiskey.dev.' },
    { from = '.local.', to = '.' },
]
